# app/sentinel/routing/failure_taxonomy.py
from enum import Enum

class FailureDomain(Enum):
    INFRASTRUCTURE = "INFRASTRUCTURE"
    CODE = "CODE"
    TOPOLOGY = "TOPOLOGY"
    UNKNOWN = "UNKNOWN"

class FailureCategory(str, Enum):
    INFRASTRUCTURE_FAILURE = "INFRASTRUCTURE_FAILURE"
    PROJECTOR_FAILURE = "PROJECTOR_FAILURE"
    COMPILER_FAILURE = "COMPILER_FAILURE"
    TOPOLOGY_FAILURE = "TOPOLOGY_FAILURE"
    RUNTIME_STATE_FAILURE = "RUNTIME_STATE_FAILURE"
    GRAPH_STATE_FAILURE = "GRAPH_STATE_FAILURE"
    UNKNOWN = "UNKNOWN"

class RoutingDecision(str, Enum):
    INFRASTRUCTURE = "INFRASTRUCTURE"
    ATLAS = "ATLAS"
    TOPOLOGY = "TOPOLOGY"
    UNKNOWN = "UNKNOWN"

class TerminalStatus(str, Enum):
    SUCCESS = "SUCCESS"
    INFRASTRUCTURE_ABORT = "INFRASTRUCTURE_ABORT"
    ATLAS_UNAVAILABLE = "ATLAS_UNAVAILABLE"
    UNREPAIRABLE_CODE_FAILURE = "UNREPAIRABLE_CODE_FAILURE"
    MAX_REPAIRS_EXCEEDED = "MAX_REPAIRS_EXCEEDED"
    VERIFICATION_PASSED = "VERIFICATION_PASSED"

class SearchOutcome(str, Enum):
    NOT_RUN = "NOT_RUN"
    NO_CANDIDATES = "NO_CANDIDATES"
    CANDIDATES_GENERATED = "CANDIDATES_GENERATED"
    CANDIDATE_SELECTED = "CANDIDATE_SELECTED"

class AtlasFailureReason(str, Enum):
    TIMEOUT = "TIMEOUT"
    EXCEPTION = "EXCEPTION"
    EMPTY_RESPONSE = "EMPTY_RESPONSE"
    INVALID_OUTPUT = "INVALID_OUTPUT"

CATEGORY_DOMAIN_MAP = {
    FailureCategory.INFRASTRUCTURE_FAILURE: FailureDomain.INFRASTRUCTURE,
    FailureCategory.PROJECTOR_FAILURE: FailureDomain.CODE,
    FailureCategory.COMPILER_FAILURE: FailureDomain.CODE,
    FailureCategory.RUNTIME_STATE_FAILURE: FailureDomain.CODE,
    FailureCategory.GRAPH_STATE_FAILURE: FailureDomain.TOPOLOGY,
    FailureCategory.TOPOLOGY_FAILURE: FailureDomain.TOPOLOGY,
    FailureCategory.UNKNOWN: FailureDomain.UNKNOWN
}

CATEGORY_PRIORITY = [
    FailureCategory.INFRASTRUCTURE_FAILURE,
    FailureCategory.PROJECTOR_FAILURE,
    FailureCategory.COMPILER_FAILURE,
    FailureCategory.RUNTIME_STATE_FAILURE,
    FailureCategory.GRAPH_STATE_FAILURE,
    FailureCategory.TOPOLOGY_FAILURE,
]
