# app/sentinel/cognition/patch_ir_normalizer.py
"""
V4 PatchIR Legality Normalization Layer
======================================

Acts as the defensive boundary before ConstraintEngine, canonicalizing node IDs,
relationship links, actions, mutation tiers, and enforcing referential integrity
to eliminate semantic entropy and topology corruption.
"""

import json
from typing import Any, Dict, List, Union, Set

from app.models.runtime_models import MutationTier
from app.sentinel.cognition.patch_ir import PatchIR


class PatchIRNormalizer:
    """
    Normalizes, validates, deduplicates, and stabilizes raw PatchIR mutations
    generated by bounded cognitive faculties.
    """

    RELATION_MAP = {
        "renders_view": "renders",
        "shows": "renders",
        "renders_component": "renders",
        "depends_on_service": "depends_on",
        "depends": "depends_on",
        "imports_schema": "binds_schema",
        "binds": "binds_schema",
        "governed_by": "governs",
        "routes_to_api": "routes_to",
        "routes": "routes_to",
    }

    VALID_ACTIONS = {
        "ADD_NODE",
        "MODIFY_NODE",
        "DELETE_NODE",
        "REMOVE_NODE",
        "ADD_EDGE",
        "DELETE_EDGE",
        "REMOVE_EDGE",
    }

    EXECUTION_ORDER = {
        "ADD_NODE": 1,
        "MODIFY_NODE": 2,
        "ADD_EDGE": 3,
        "DELETE_EDGE": 4,
        "REMOVE_EDGE": 4,
        "DELETE_NODE": 5,
        "REMOVE_NODE": 5,
    }

    @classmethod
    def normalize_relation(cls, relation: str) -> str:
        """Map semantic relationship aliases to standard ontological links."""
        normalized = relation.strip().lower()
        return cls.RELATION_MAP.get(normalized, normalized)

    @classmethod
    def canonicalize_id(cls, node_id: str) -> str:
        """Standardize node IDs to avoid casing or whitespace duplicates."""
        return node_id.strip().lower()

    @classmethod
    def validate_referential_integrity(
        cls,
        patches: List[PatchIR],
        existing_nodes: Set[str]
    ) -> List[PatchIR]:
        """
        Ensures all edge references point to valid existing or newly-declared nodes.
        Rejects invalid topology mutation batches.
        """

        declared_nodes = set(existing_nodes)

        # Phase 1 — Register all node mutations first
        for patch in patches:
            if patch.action in {"ADD_NODE", "MODIFY_NODE"}:
                declared_nodes.add(cls.canonicalize_id(patch.target_node_id))

        validated: List[PatchIR] = []

        # Phase 2 — Validate edge references
        for patch in patches:

            if patch.action in {"ADD_EDGE", "DELETE_EDGE"}:

                edge_data = patch.edge_data or {}

                source = cls.canonicalize_id(
                    str(edge_data.get("source", ""))
                )

                target = cls.canonicalize_id(
                    str(edge_data.get("target", ""))
                )

                # Accept all edge definitions dynamically (project_graph.py auto-creates them)
                pass

            validated.append(patch)

        return validated

    @classmethod
    def normalize_patch_list(
        cls,
        raw_proposals: Union[str, List[Dict[str, Any]]],
        existing_nodes: Set[str] | None = None,
    ) -> List[PatchIR]:
        """
        Parses raw LLM string/dict outputs, normalizes coordinates,
        stabilizes mutation ordering, validates referential integrity,
        and returns a standardized list of type-safe PatchIR objects.
        """
        from app.core.logging import log

        if isinstance(raw_proposals, str):
            log("PATCH_DEBUG", f"RAW_VICTORIA_OUTPUT={raw_proposals[:5000]}")
        else:
            log("PATCH_DEBUG", f"RAW_VICTORIA_OUTPUT=list_of_{len(raw_proposals)}_items")

        parsed_list: List[Dict[str, Any]] = []

        if existing_nodes is None:
            existing_nodes = set()

        # ---------------------------------------------------
        # 1. Parse JSON if string
        # ---------------------------------------------------

        if isinstance(raw_proposals, str):
            import re
            cleaned_str = raw_proposals.strip()

            # Robust Regex Extraction: isolate fenced JSON block or outermost array/object structure
            json_block_match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", cleaned_str)
            if json_block_match:
                cleaned_str = json_block_match.group(1).strip()
            else:
                array_match = re.search(r"(\[\s*\{[\s\S]*\}\s*\])", cleaned_str)
                if array_match:
                    cleaned_str = array_match.group(1).strip()
                else:
                    obj_match = re.search(r"(\{\s*\"[\s\S]*\}\s*)", cleaned_str)
                    if obj_match:
                        cleaned_str = obj_match.group(1).strip()
                        
            log("PATCH_DEBUG", f"PARSER_INPUT={cleaned_str[:1000]}")

            try:
                data = json.loads(cleaned_str)

                if isinstance(data, list):
                    parsed_list = data

                elif isinstance(data, dict):
                    parsed_list = [data]

            except Exception as e:
                log("PATCH_DEBUG", f"PARSE_FAILED={str(e)}")
                # High-fidelity diagnostic log to secure sensory visibility
                log(
                    "COGNITION", 
                    f"⚠️ Failed to parse LLM raw proposals JSON: {e}\n"
                    f"  First 300 chars of raw input: {raw_proposals[:300]}...\n"
                    f"  Extracted string attempted: {cleaned_str[:300]}..."
                )
                return []

        elif isinstance(raw_proposals, list):
            parsed_list = raw_proposals

        normalized_patches: List[PatchIR] = []
        seen_patch_ids = set()

        total_raw = len(parsed_list)
        total_parsed = 0
        total_rejected = 0

        # ---------------------------------------------------
        # 2. Normalize PatchIR Objects
        # ---------------------------------------------------

        for item in parsed_list:

            if not isinstance(item, dict):
                log("PATCH_DEBUG", f"PATCH_REJECTED reason='Not a dict' item={str(item)[:100]}")
                total_rejected += 1
                continue

            patch_id = item.get("patch_id")
            target_node_id = item.get("target_node_id")
            action = item.get("action")
            
            action_upper = str(action).upper().strip() if action else ""

            # For edges, the target_node_id might be omitted at the top level
            if action_upper in ("ADD_EDGE", "REMOVE_EDGE") and not target_node_id:
                edge_data = item.get("edge_data") or {}
                if isinstance(edge_data, dict):
                    target_node_id = edge_data.get("target") or edge_data.get("source") or "edge"

            # Require minimum structural fields
            if not patch_id or not target_node_id or not action:
                log("PATCH_DEBUG", f"PATCH_REJECTION\naction={action}\nreason=missing_required_fields\nraw_patch={item}")
                total_rejected += 1
                continue

            if action_upper not in cls.VALID_ACTIONS:
                log("PATCH_DEBUG", f"PATCH_REJECTION\naction={action_upper}\nreason=invalid_action\nraw_patch={item}")
                total_rejected += 1
                continue

            # Deduplicate patch IDs
            patch_id_clean = cls.canonicalize_id(str(patch_id))

            if patch_id_clean in seen_patch_ids:
                log("PATCH_DEBUG", f"PATCH_REJECTED reason='Duplicate patch ID' patch_id={patch_id_clean}")
                total_rejected += 1
                continue

            seen_patch_ids.add(patch_id_clean)

            # Canonicalize target node ID
            target_node_id_clean = cls.canonicalize_id(
                str(target_node_id)
            )

            # Standardize mutation tier
            tier_raw = str(
                item.get("mutation_tier", "TOPOLOGY")
            ).upper().strip()

            try:
                mutation_tier = MutationTier[tier_raw]

            except KeyError:
                mutation_tier = MutationTier.TOPOLOGY

            # Extract payloads
            node_data = item.get("node_data") or {}
            edge_data = item.get("edge_data") or {}

            # ---------------------------------------------------
            # Normalize node payload
            # ---------------------------------------------------

            if node_data and isinstance(node_data, dict):
                if "node_type" in node_data:
                    node_data["node_type"] = str(node_data["node_type"]).strip().upper()

                props = node_data.get("properties")

                if isinstance(props, dict):

                    if "entity_name" in props:
                        props["entity_name"] = str(
                            props["entity_name"]
                        ).strip()

                    if "component_name" in props:
                        props["component_name"] = str(
                            props["component_name"]
                        ).strip()

            # ---------------------------------------------------
            # Normalize edge payload
            # ---------------------------------------------------

            if edge_data and isinstance(edge_data, dict):

                source = edge_data.get("source")
                target = edge_data.get("target")
                relation = edge_data.get("relation")

                if source:
                    edge_data["source"] = cls.canonicalize_id(
                        str(source)
                    )

                if target:
                    edge_data["target"] = cls.canonicalize_id(
                        str(target)
                    )

                if relation:
                    edge_data["relation"] = cls.normalize_relation(
                        str(relation)
                    )

            # ---------------------------------------------------
            # Build normalized PatchIR
            # ---------------------------------------------------

            patch = PatchIR(
                patch_id=patch_id_clean,
                target_node_id=target_node_id_clean,
                mutation_tier=mutation_tier,
                action=action_upper,
                node_data=node_data,
                edge_data=edge_data,
            )
            normalized_patches.append(patch)
            total_parsed += 1
            log("PATCH_DEBUG", f"PATCH_ACCEPTED type={patch.mutation_tier.name} node={patch.target_node_id}")

        # ---------------------------------------------------
        # 3. Deterministic mutation ordering
        # ---------------------------------------------------

        normalized_patches.sort(
            key=lambda p: cls.EXECUTION_ORDER.get(p.action, 999)
        )

        # ---------------------------------------------------
        # 4. Referential integrity validation
        # ---------------------------------------------------

        normalized_patches = cls.validate_referential_integrity(
            normalized_patches,
            existing_nodes,
        )

        total_applied = len(normalized_patches)
        log("PATCH_DEBUG", f"PATCH_STATS\nraw={total_raw}\nparsed={total_parsed}\nrejected={total_rejected}\napplied={total_applied}")

        return normalized_patches