# app/studio/architecture/application_architect.py
"""
V4 GenxAI Studio — Phase GS-1: ApplicationArchitect

The ApplicationArchitect is the core generative faculty of GenxAI Studio.
It strictly consumes the OntologyGraph generated by Sentinel, mapping abstract entities,
roles, capabilities, and workflows into an in-memory ApplicationGraph layout hierarchy.
Strictly in-memory; no physical files or components are written.
"""

import json
from typing import Dict, Any, Optional, List
from app.sentinel.cognition.ontology_graph import OntologyGraph
from app.studio.architecture.application_graph import ApplicationGraph
from app.sentinel.topology.node_types import NodeType
from app.llm.adapter import call_llm
from app.core.logging import log

PROMPT_TEMPLATE = """
You are the GenxAI Studio Application Architect Faculty.
Your task is to analyze the abstract Product Ontology Graph (Entities, Roles, Capabilities, Workflows)
and generate a high-level logical Application Architecture Graph.

Do NOT output React code, TSX components, HTML layouts, or styling details.
Focus exclusively on the abstract structure of the application:
1. Workspace: The high-level name and purpose of the workspace (e.g. Sales CRM, Finance Tracker).
2. Pages: The logical views or pages that should exist (e.g. Dashboard, Accounts, Contacts, Settings).
3. Features: Abstract features or interactive panels mapped to specific pages (e.g. Search, Filters, Export, Activity Feed).
4. Page Relationships: Logical transitions or relational associations between pages (e.g. Accounts connects to Contacts).
5. Navigation Layout: The core layout style (e.g. Sidebar, Navbar, Tabs).

Based on the following Product Ontology Graph:
{ontology_graph_json}

Produce a valid JSON object matching this schema exactly:
{{
  "application": {{
    "workspace_name": "Sales CRM",
    "navigation_style": "Sidebar",
    "pages": [
      {{
        "id": "page_dashboard",
        "name": "Dashboard",
        "features": ["Activity Feed"]
      }},
      {{
        "id": "page_accounts",
        "name": "Accounts",
        "features": ["Search", "Filters", "Export"]
      }}
    ],
    "page_relationships": [
      {{
        "source": "page_accounts",
        "target": "page_contacts"
      }}
    ]
  }}
}}

Ensure all fields are present, and generate ONLY valid JSON without any markdown formatting or surrounding explanations.
"""

class ApplicationArchitect:
    """
    Ingests an OntologyGraph and synthesizes a structured, in-memory ApplicationGraph layout.
    """

    @classmethod
    async def build(cls, project_id: str, ontology_graph: OntologyGraph) -> ApplicationGraph:
        """
        Synthesize the high-level application structure based strictly on the input OntologyGraph.
        """
        log("ApplicationArchitect", f"Starting application architecture generation for project {project_id}")
        
        # 1. Prepare Ontology Graph summary
        ont_graph_dump = ontology_graph.serialize()

        # 2. Call LLM for Application Graph synthesis
        system_prompt = "You are a software application architect specialized in visual layouts and page structures."
        prompt = PROMPT_TEMPLATE.format(ontology_graph_json=json.dumps(ont_graph_dump, indent=2))

        try:
            response = await call_llm(
                prompt=prompt,
                system_prompt=system_prompt,
                step_name="application_architecture_reasoning",
                max_tokens=16384  # Keep within safe token bounds
            )

            # Clean possible markdown formatting
            if response.startswith("```json"):
                response = response[7:]
            if response.endswith("```"):
                response = response[:-3]

            data = json.loads(response.strip())
            
            app_graph = ApplicationGraph(project_id=project_id)
            cls._populate_app_graph(app_graph, data, ontology_graph)

            log("ApplicationArchitect", f"Successfully synthesized ApplicationGraph with {len(app_graph.nodes)} nodes")
            return app_graph

        except Exception as e:
            log("ApplicationArchitect", f"⚠️ LLM application architecture synthesis failed: {e}. Falling back to deterministic parser.")
            # Resilient fallback parsing to prevent hard errors
            return cls._fallback_parsing(project_id, ontology_graph)

    @classmethod
    def _populate_app_graph(
        cls,
        graph: ApplicationGraph,
        data: Dict[str, Any],
        ontology_graph: OntologyGraph
    ) -> None:
        """Parses synthesized architect layout JSON and populates the ApplicationGraph."""
        app_data = data.get("application", {})
        
        workspace_name = app_data.get("workspace_name", "App Workspace")
        nav_style = app_data.get("navigation_style", "Sidebar")
        
        # 1. Create Workspace Node
        workspace_id = f"workspace_{graph.project_id}"
        graph.add_application_node(
            workspace_id,
            NodeType.WORKSPACE_NODE,
            {"name": workspace_name}
        )

        # 2. Create Navigation Layout Node
        nav_id = f"nav_layout_{graph.project_id}"
        graph.add_application_node(
            nav_id,
            NodeType.NAV_LAYOUT_NODE,
            {"style": nav_style}
        )
        graph.add_edge(workspace_id, nav_id, "page_uses_layout")

        # 3. Create Page & Feature Nodes
        for page in app_data.get("pages", []):
            page_id = page.get("id")
            page_name = page.get("name")
            if page_id and page_name:
                # Add Page Node
                graph.add_application_node(
                    page_id,
                    NodeType.PAGE_NODE,
                    {"name": page_name}
                )
                graph.add_edge(workspace_id, page_id, "workspace_contains_page")
                graph.add_edge(page_id, nav_id, "page_uses_layout")

                # Add mapped Features
                for feature_name in page.get("features", []):
                    feature_id = f"feat_{page_id}_{feature_name.lower().replace(' ', '_')}"
                    graph.add_application_node(
                        feature_id,
                        NodeType.FEATURE_NODE,
                        {"name": feature_name}
                    )
                    graph.add_edge(page_id, feature_id, "page_contains_feature")

        # 4. Create Page Relations
        for rel in app_data.get("page_relationships", []):
            src = rel.get("source")
            tgt = rel.get("target")
            if src in graph.nodes and tgt in graph.nodes:
                graph.add_edge(src, tgt, "page_relates_to")

    @classmethod
    def _fallback_parsing(cls, project_id: str, ontology_graph: OntologyGraph) -> ApplicationGraph:
        """
        Deterministic parser that reads entities, roles, and workflows from the OntologyGraph
        and generates a highly coherent workspace layout without requiring active LLM calls.
        """
        log("ApplicationArchitect", "Running deterministic fallback application architecture parser.")
        
        graph = ApplicationGraph(project_id=project_id)
        
        # 1. Create Workspace
        workspace_id = f"workspace_{project_id}"
        graph.add_application_node(
            workspace_id,
            NodeType.WORKSPACE_NODE,
            {"name": f"Generated {project_id.capitalize()} Workspace"}
        )

        # 2. Create Layout
        nav_id = f"nav_layout_{project_id}"
        graph.add_application_node(
            nav_id,
            NodeType.NAV_LAYOUT_NODE,
            {"style": "Sidebar"}
        )
        graph.add_edge(workspace_id, nav_id, "page_uses_layout")

        # 3. Create Dashboard Page (Standard first view)
        dashboard_id = "page_dashboard"
        graph.add_application_node(
            dashboard_id,
            NodeType.PAGE_NODE,
            {"name": "Dashboard"}
        )
        graph.add_edge(workspace_id, dashboard_id, "workspace_contains_page")
        graph.add_edge(dashboard_id, nav_id, "page_uses_layout")
        
        # Add Activity Feed feature to Dashboard
        feat_feed_id = "feat_page_dashboard_activity_feed"
        graph.add_application_node(
            feat_feed_id,
            NodeType.FEATURE_NODE,
            {"name": "Activity Feed"}
        )
        graph.add_edge(dashboard_id, feat_feed_id, "page_contains_feature")

        # 4. Map each Entity in OntologyGraph to a unique Page
        entity_pages = []
        for node_id, node in ontology_graph.nodes.items():
            if node.node_type == NodeType.ENTITY_NODE:
                page_id = f"page_{node_id.lower()}"
                page_name = node.properties.get("name", "Item")
                # Pluralize name
                if not page_name.endswith("s"):
                    page_name = page_name + "s"
                    
                graph.add_application_node(
                    page_id,
                    NodeType.PAGE_NODE,
                    {"name": page_name}
                )
                graph.add_edge(workspace_id, page_id, "workspace_contains_page")
                graph.add_edge(page_id, nav_id, "page_uses_layout")
                
                # Add default features (Search, Filters)
                feat_search = f"feat_{page_id}_search"
                graph.add_application_node(
                    feat_search,
                    NodeType.FEATURE_NODE,
                    {"name": "Search"}
                )
                graph.add_edge(page_id, feat_search, "page_contains_feature")

                feat_filter = f"feat_{page_id}_filters"
                graph.add_application_node(
                    feat_filter,
                    NodeType.FEATURE_NODE,
                    {"name": "Filters"}
                )
                graph.add_edge(page_id, feat_filter, "page_contains_feature")
                
                entity_pages.append(page_id)

        # 5. Create basic relations between discovered pages
        for page_id in entity_pages:
            graph.add_edge(dashboard_id, page_id, "page_relates_to")

        # 6. Map relationships from OntologyGraph
        for rel_id, node in ontology_graph.nodes.items():
            if node.node_type == NodeType.RELATIONSHIP_NODE:
                # Find connected entities/roles
                edges = [e for e in ontology_graph.edges if e.source_id == rel_id or e.target_id == rel_id]
                source_ent = None
                target_ent = None
                for e in edges:
                    if e.source_id == rel_id and e.relation == "ontology_relates_to":
                        target_ent = e.target_id
                    elif e.target_id == rel_id and e.relation == "ontology_relates_to":
                        source_ent = e.source_id
                
                if source_ent and target_ent:
                    src_page = f"page_{source_ent.lower()}"
                    tgt_page = f"page_{target_ent.lower()}"
                    if src_page in graph.nodes and tgt_page in graph.nodes:
                        graph.add_edge(src_page, tgt_page, "page_relates_to")

        # 7. Add Settings Page
        settings_id = "page_settings"
        graph.add_application_node(
            settings_id,
            NodeType.PAGE_NODE,
            {"name": "Settings"}
        )
        graph.add_edge(workspace_id, settings_id, "workspace_contains_page")
        graph.add_edge(settings_id, nav_id, "page_uses_layout")

        return graph
