# app/core/types.py
"""
Shared type definitions used across the application.

CONSOLIDATED from:
- types.py (original)
- step_outcome.py (merged 2025-12-29)
- guard.py (merged 2025-12-29)
"""
from dataclasses import dataclass, field
from typing import Any, Dict, List, Literal, Optional, TypedDict
from enum import Enum
from pathlib import Path
from app.core.time import utc_now


# ═══════════════════════════════════════════════════════════════════════════
# ORCHESTRATION GUARD (from guard.py)
# ═══════════════════════════════════════════════════════════════════════════

class OrchestrationGuard:
    """
    Safety lock to prevent accidental re-introduction of cognitive decisions
    (retries, escalation, healing) into the orchestration layer.
    
    COGNITIVE LOGIC BELONGS IN SENTINEL GOVERNOR ONLY.
    """
    def __getattr__(self, name):
        raise RuntimeError(
            f"Orchestration attempted cognitive decision: {name}. "
            "COGNITIVE LOGIC BELONGS IN ORCHESTRATOR ONLY."
        )


# ═══════════════════════════════════════════════════════════════════════════
# STEP OUTCOMES (from step_outcome.py)
# ═══════════════════════════════════════════════════════════════════════════

class StepOutcome(Enum):
    """Step-level outcomes (4 types only)."""
    SUCCESS = "success"
    HARD_FAILURE = "hard_failure"           # Logical impossibility (GLOBAL)
    COGNITIVE_FAILURE = "cognitive_failure" # Agent mistake (healable)
    ENVIRONMENT_FAILURE = "environment_failure" # Platform constraint


@dataclass
class StepExecutionResult:
    """Result of a single step execution."""
    outcome: StepOutcome
    step_name: str = ""
    isolated: bool = False  # True if quarantined (dead branch)
    artifacts: List[Path] = field(default_factory=list)
    data: Dict[str, Any] = field(default_factory=dict)
    error_details: Optional[str] = None
    tool_used: Optional[str] = None
    
    def is_successful(self) -> bool:
        """Only SUCCESS counts as success."""
        return self.outcome == StepOutcome.SUCCESS
    
    def requires_healing(self) -> bool:
        """Only COGNITIVE_FAILURE triggers healing."""
        return self.outcome == StepOutcome.COGNITIVE_FAILURE
    
    def is_dead_branch(self) -> bool:
        """Isolated steps are dead branches."""
        return self.isolated
    
    def is_hard_failure(self) -> bool:
        """HARD_FAILURE is a global truth (ignores isolation)."""
        return self.outcome == StepOutcome.HARD_FAILURE


@dataclass
class StepExecutionRecord:
    """
    Record of what a step produced during execution.
    
    Used for:
    - Rollback (delete files created by failed step)
    - Resume (know what each step created)
    - Debugging (audit trail)
    """
    step_name: str
    files_created: List[str] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: utc_now().isoformat())
    attempt_number: int = 1  # 1 = first attempt, 2 = retry
    
    def to_dict(self) -> dict:
        """Serialize for checkpoint persistence."""
        return {
            "step_name": self.step_name,
            "files_created": self.files_created,
            "timestamp": self.timestamp,
            "attempt_number": self.attempt_number
        }
    
    @classmethod
    def from_dict(cls, data: dict) -> "StepExecutionRecord":
        """Deserialize from checkpoint."""
        return cls(
            step_name=data.get("step_name", ""),
            files_created=data.get("files_created", []),
            timestamp=data.get("timestamp", ""),
            attempt_number=data.get("attempt_number", 1)
        )


# ═══════════════════════════════════════════════════════════════════════════
# ORIGINAL TYPES.PY CONTENT
# ═══════════════════════════════════════════════════════════════════════════

# TypedDict for chat messages
class ChatMessage(TypedDict):
    role: str
    content: str





# File output from agents (dataclass version)
@dataclass
class GeneratedFile:
    """A file generated by an agent."""
    path: str
    content: str
    
    def to_dict(self) -> Dict[str, str]:
        return {"path": self.path, "content": self.content}



# Agent output structure
@dataclass
class AgentOutput:
    """Output from an agent call."""
    files: List[GeneratedFile] = field(default_factory=list)
    thinking: str = ""
    raw: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "files": [f.to_dict() for f in self.files],
            "thinking": self.thinking,
        }





# Workflow step result
@dataclass
class StepResult:
    """Result of executing a workflow step."""
    nextstep: str
    turn: int
    pause: bool = False
    status: str = "ok"
    data: Dict[str, Any] = field(default_factory=dict)
    token_usage: Optional[Dict[str, int]] = None  # V3: {"input": int, "output": int}
    error: Optional[str] = None  # For transient infrastructure failures (e.g., Gemini 503)


# Quality metrics
@dataclass
class QualityMetrics:
    """Quality metrics for a project."""
    total_files: int = 0
    total_lines: int = 0
    avg_quality_score: float = 0.0
    approvals: int = 0
    rejections: int = 0


# Token usage for cost tracking
@dataclass
class TokenUsage:
    """Track token usage for cost estimation."""
    input_tokens: int = 0
    output_tokens: int = 0
    
    @property
    def total(self) -> int:
        return self.input_tokens + self.output_tokens
    
    @property
    def estimated_cost(self) -> float:
        """Estimate cost based on Gemini pricing."""
        input_cost = (self.input_tokens / 1000) * 0.00025
        output_cost = (self.output_tokens / 1000) * 0.0005
        return round(input_cost + output_cost, 6)


# Workflow state
class WorkflowStatus(Enum):
    """
    Workflow-level outcomes (aggregate property).
    
    Phase 1: Updated to support degradation reporting.
    """
    RUNNING = "running"
    PAUSED = "paused"
    SUCCESS = "success"                              # Clean success (all steps passed)
    SUCCESS_WITH_DEGRADATION = "success_with_degradation"  # NEW: Degraded but coherent
    FAILED = "failed"
    
    # Legacy alias for backward compatibility
    COMPLETED = "success"


@dataclass
class DegradationReport:
    """
    Report for workflows that complete with degradation.
    
    Phase 1: This is an AGGREGATE property, not step-level.
    Degradation means some steps were isolated (dead branches).
    """
    isolated_steps: List[str]                      # Steps that were quarantined
    quarantined_artifacts: Dict[str, List[str]]    # Artifacts that are untrusted
    alternative_evidence: Dict[str, Any]           # Evidence from static validation
    message: str                                   # Human-readable summary





# ============================================================
# TypedDict types (from legacy agents/types.py)
# ============================================================




class QAIssue(TypedDict):
    """Quality assurance issue from Derek/Luna."""
    file: str
    line: int
    area: str
    description: str
    severity: Literal['critical', 'major', 'minor']
    suggested_fix: str
    codeContext: Optional[str]
    testableImpact: Optional[str]


class FilePlan(TypedDict):
    """File plan for workflow."""
    path: str
    description: str


class TestReport(TypedDict):
    """Test report from QA agents."""
    summary: str
    passed: bool
    issueCount: Optional[int]
    severityBreakdown: Optional[Dict[str, int]]
    issues: List[QAIssue]
    recommendations: Optional[List[str]]


class ToolCall(TypedDict):
    """A tool call from Marcus."""
    name: str
    args: Dict[str, Any]


class MarcusPlan(TypedDict):
    """Marcus's planning output."""
    thought: str
    tool_call: Optional[ToolCall]
    speak_to_user: Optional[str]

